# run entries for Arabic

entries: [
  {description: "arabic_content_generation:category=all"},
  {description: "arabic_legal_qa"},
  {description: "arabic_legal_rag"},
  {description: "arabic_finance_bool"},
  {description: "arabic_finance_calculation"},
  {description: "arabic_finance_mcq"},
]
