# run entries for Arabic

entries: [
  {description: "arabic_content_generation:category=all"},
  {description: "arabic_finance_mcq:lang=ar"},
  {description: "arabic_finance_bool:lang=ar"},
  {description: "arabic_finance_calculation:lang=ar"},
  {description: "arabic_finance_mcq:lang=en"},
  {description: "arabic_finance_bool:lang=en"},
  {description: "arabic_finance_calculation:lang=en"},
]
