# run entries for Arabic that have context

entries: [
  # ArabicMMLU
  {description: "arabic_mmlu:subset=Arabic_Language_(General),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},
  {description: "arabic_mmlu:subset=Arabic_Language_(High_School),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},
  {description: "arabic_mmlu:subset=Geography_(High_School),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},
  {description: "arabic_mmlu:subset=Geography_(Middle_School),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},
  {description: "arabic_mmlu:subset=Islamic_Studies_(Primary_School),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},

  # MadinahQA
  {description: "madinah_qa:subset=Arabic_Language_(General),output_format_instructions=arabic_mcqa,max_train_instances=0", priority: 1},
]
